name: Build & Deploy

on:
  push:
  schedule:
    - cron: '0 0 5 * *'

jobs:
  test:
    name: Test Vercel URL Action
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Preview URL
        uses: zentered/vercel-preview-url@v1.1.1
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ''
          vercel_project_id: 'prj_VGsbMBHmakJlktyjWghOGD41eJEL'
