name: Integration Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 5 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Wait for Vercel Preview URL with App Name
        id: vercel_preview_url_by_name
        uses: zentered/vercel-preview-url@v1.4.0
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_REF: 'main'
          GITHUB_REPOSITORY: 'PatrickHeneise/vercel-preview-action-test'
        with:
          vercel_app: 'vercel-preview-action-test'
      - name: Get URL
        run:
          echo "https://${{
          steps.vercel_preview_url_by_name.outputs.preview_url}}"
